kind: pipeline
name: test

clone:
  depth: 50

workspace:
  base: /go
  path: src/github.com/mleyb/goserve

steps:
  - name: testing
    image: golang:latest
    pull: true
    commands:
      - go get
      - go vet
      - go test -coverprofile cp.out

---
kind: pipeline
name: build

clone:
  depth: 50

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: mleybourne/goserve
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

depends_on:
  - test
