workspace:
  base: /go
  path: src/github.com/mleyb/goserve

pipeline:
  test:
    image: golang:latest
    commands:
      - go get
      - go vet
      - go test -v -cover
  build:
    image: golang:latest
    commands:
      - go get
      - go build
  docker:
    image: plugins/docker
    settings:
      repo: mleybourne/goserve
      secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
      tags: latest
