workspace:
  base: /go
  path: src/github.com/mleyb/goserve

pipeline:
  test:
    image: golang:latest
    commands:
      - go get
      - go vet
      - go test -v -cover
  build:
    image: golang:latest
    commands:
      - go get
      - go build
  docker-build:
    image: docker
    commands:
      - docker build \
        --label org.label-schema.build-date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
        --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD) \
        .
